### ISSUE TITLE
Error configuring mamba/conda environment using `environment.yml`

### ISSUE THREAD

**Issue by geek-yang** [EcoExtreML/STEMMUS_SCOPE_Processing#47]
When configuring the conda environment on Snellius using `environment.yml` file with the following command:

`mamba env create -f environment.yml`

An error was thrown by `pip` when installing the dependencies of `pystemmusscope`:

```py
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Installing pip dependencies: / Ran pip subprocess with arguments:
['/gpfs/home3/yangl/mamba/envs/pystemmusscope/bin/python', '-m', 'pip', 'install', '-U', '-r', '/gpfs/home3/yangl/STEMMUS_SCOPE_Processing/condaenv.3m4jxwnv.requirements.txt']
Pip subprocess output:
Collecting git+https://github.com/EcoExtreML/STEMMUS_SCOPE_Processing.git@main (from -r /gpfs/home3/yangl/STEMMUS_SCOPE_Processing/condaenv.3m4jxwnv.requirements.txt (line 1))
  Cloning https://github.com/EcoExtreML/STEMMUS_SCOPE_Processing.git (to revision main) to /gpfs/scratch1/nodespecific/int3/yangl/pip-req-build-i295xy42
  Resolved https://github.com/EcoExtreML/STEMMUS_SCOPE_Processing.git to commit d34f8f9c6f6802097be378660124340f2bb81a49
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting hdf5storage
  Using cached hdf5storage-0.1.18-py2.py3-none-any.whl (53 kB)
Collecting netcdf4
  Using cached netCDF4-1.6.1.tar.gz (776 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'

Pip subprocess error:
  Running command git clone --filter=blob:none --quiet https://github.com/EcoExtreML/STEMMUS_SCOPE_Processing.git /gpfs/scratch1/nodespecific/int3/yangl/pip-req-build-i295xy42
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [43 lines of output]
      Package hdf5 was not found in the pkg-config search path.
      Perhaps you should add the directory containing `hdf5.pc'
      to the PKG_CONFIG_PATH environment variable
      Package 'hdf5', required by 'virtual:world', not found
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/gpfs/scratch1/nodespecific/int3/yangl/pip-install-jga8h11p/netcdf4_d7ef60ea8dac423a9acb362bb8cf40eb/setup.py", line 463, in <module>
          raise ValueError('did not find netCDF version 4 headers')
      ValueError: did not find netCDF version 4 headers
      reading from setup.cfg...

          HDF5_DIR environment variable not set, checking some standard locations ..
      checking /gpfs/home3/yangl/mamba/envs/pystemmusscope/include ...
      hdf5 headers not found in /gpfs/home3/yangl/mamba/envs/pystemmusscope/include
      checking /gpfs/home3/yangl/mamba/envs/pystemmusscope/Library/include ...
      hdf5 headers not found in /gpfs/home3/yangl/mamba/envs/pystemmusscope/Library/include
      checking /home/yangl/include ...
      hdf5 headers not found in /home/yangl/include
      checking /usr/local/include ...
      hdf5 headers not found in /usr/local/include
      checking /sw/include ...
      hdf5 headers not found in /sw/include
      checking /opt/include ...
      hdf5 headers not found in /opt/include
      checking /opt/local/include ...
      hdf5 headers not found in /opt/local/include
      checking /opt/homebrew/include ...
      hdf5 headers not found in /opt/homebrew/include
      checking /usr/include ...
      HDF5 library version: 1.10.5 headers found in /usr/include
      HDF5 library version: 1.10.5 found in /usr

      NETCDF4_DIR environment variable not set, checking standard locations..
      checking /gpfs/home3/yangl/mamba/envs/pystemmusscope ...
      checking /gpfs/home3/yangl/mamba/envs/pystemmusscope/Library ...
      checking /home/yangl ...
      checking /usr/local ...
      checking /sw ...
      checking /opt ...
      checking /opt/local ...
      checking /opt/homebrew ...
      checking /usr ...
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

failed

CondaEnvException: Pip failed
```

After some googling, it seems this error is due to the fact that hdf5 library is not installed. Adding `h5py` to the dependency list might fix this. I will test it.

**Comment by geek-yang** [comment]
Adding `h5py` doesn't help. But the installation went smoothly for me when using `environment_3.8.yml` with the same command. The only difference is the version of python. When executing `environment.yml`, python3.11.0 is installed. Then it is clear, that python3.11.0 is the cause for this failure. Perhaps `netcdf4` is not ready yet for the latest version of python. I would suggest to make `python<=3.10` in the `environment.yml` file.

**Comment by SarahAlidoost** [comment]
Please consider the related issue #43.
